version: '3'
services:
    dynamodb:
        image: amazon/dynamodb-local
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
        volumes:
            - dynamodb:/home/dynamodblocal
        ports:
            - 8001:8000
        networks:
            - lambda-local
    awscli:
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: [""]
        tty: true
        command:
            - /bin/sh
        volumes:
            - ./bin:/usr/app
        networks:
            - lambda-local
volumes:
    dynamodb:
        driver: local
    bin:
        driver: local
networks:
    lambda-local:
        external: true